### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'string' of undefined"

### ISSUE THREAD

**Issue by kirpalmakanga** [voronianski/react-pikaday-component#18]
Happens when importing the component. Seems like _react.PropTypes is not defined in index.js

**Comment by kkollman** [comment]
I came across the same issue. It seems to me that the cause is that `react-pikaday-component` isn't updated to React 16 yet.

**Comment by gilbert** [comment]
It's fixed in master, but @voronianski needs to rebuild and publish a new version.

**Comment by Melonbwead** [comment]
Bump~! @voronianski you able to publish master to a new version ?

**Comment by ViggoV** [comment]
Any news on this?

**Comment by Benji-Leboe** [comment]
Yooo it's 2019 and this issue still hasn't been fixed... what's the issue

**Comment by nickmcmillan** [comment]
2020 now and the problem still exists. 

I'm trying to migrate an existing codebase from React 15 to 16, and this package is holding me back.

Did anyone have any luck, or alternatives?
